environment:
  matrix:
  - ver: 4
  - ver: 5
install:
- curl -sLo mql.exe https://github.com/EA31337/FX-MT-VM/releases/download/4.x/mql.exe
- git clone -q --recursive https://github.com/EA31337/EA31337-strategies MQL%ver%/include/EA31337-strategies
before_test:
- mklink /D "MQL%ver%\include\EA31337-classes" "%cd%"
- pwd
test_script:
- echo %errorlevel%
- forfiles /m *.mqh /c "mql /s /mql%ver% @path"
- echo %errorlevel%
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build: off
platform: x86
